# Generated by Django 4.2.3 on 2023-07-28 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('categoryName', models.CharField(max_length=100)),
                ('productImg', models.ImageField(blank=True, null=True, upload_to='media/product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
