# Generated by Django 4.2.3 on 2023-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
