# Generated by Django 4.2.3 on 2023-07-26 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_users_profilepic_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Phonenumber', models.IntegerField(blank=True, null=True)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='media/profile')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
